# ------------------------------------------------------------------------------------------------------------------------
# Pipeline Template to deploy Azure Resources Only
# ------------------------------------------------------------------------------------------------------------------------
parameters:
- name: environments
  type: object
  default: ['DEV'] # or ['DEV','QA'] or ['DEV','QA','PROD'] or ['DEV','QA','STG','PROD']
- name: variableGroupName
  default: 'myVariableGroupName'

# ----------------------------------------------------------------------------------------------------
stages:
- ${{ each environmentName in parameters.environments }} :
  - stage: CreateInfrastructure${{ environmentName }}
    displayName: ${{ environmentName }} Infrastructure
    jobs:
    - template: templates/create-infra-template.yml
      parameters:
        variableGroupName: ${{ parameters.variableGroupName }}
        environmentName: ${{ environmentName }}
