# ----------------------------------------------------------------------------------------------------
# Template to deploy Azure Resources for one environment
# ----------------------------------------------------------------------------------------------------
parameters: 
- name: variableGroupName
  default: ''
- name: environmentName
  default: 'DEV'
- name: templateFolderName
  default: 'Infrastructure/bicep'
- name: templateFileName
  default: 'main.bicep'
  
# ----------------------------------------------------------------------------------------------------
jobs:
- deployment: Create${{ parameters.environmentName }}Infra
  displayName: Initialize ${{ parameters.environmentName }} Create Infra
  environment: ${{ parameters.environmentName }}

- job: Create${{ parameters.environmentName }}InfraJob
  displayName: Create ${{ parameters.environmentName }} Infrastructure
  variables:
    - group: ${{ parameters.variableGroupName }}
    - name: environmentNameUpper
      value: ${{ upper(parameters.environmentName) }}
    - name: environmentNameLower
      value: ${{ lower(parameters.environmentName) }}
    - name: templateFile
      value: '$(Pipeline.Workspace)/s/${{ parameters.templateFolderName }}/${{ parameters.templateFileName }}'

  steps:
  - bash: |
      appPrefixLower=$(echo "$(appPrefix)" | tr '[:upper:]' '[:lower:]')
      echo "##vso[task.setvariable variable=appPrefixLower]$appPrefixLower"

      runDateTime=$(echo $(date '+%Y%m%d-%H%M%S'))
      echo "##vso[task.setvariable variable=runDateTime]$runDateTime"
      echo "runDateTime=$runDateTime"
    displayName: 'Create Variables'

  - bash: |
      echo "environmentNameUpper=$(environmentNameUpper)"
      echo "environmentNameLower=$(environmentNameLower)"
      echo "resourceGroupName=$(resourceGroupName)"
      echo "azureSubscription=$(azureSubscription)"
      echo "azureSubscriptionId=$(azureSubscriptionId)"
      echo "region=$(region)"
      echo "orgPrefix=$(orgPrefix)"
      echo "appPrefix=$(appPrefix)"
      echo "appPrefixLower=$(appPrefixLower)"
      echo "templateFile=$(templateFile)"
      tree $(Pipeline.Workspace)
    displayName: 'Display Variables'
    continueOnError: true

  - task: AzureCLI@2
    displayName: 'Create Resource Group if not exists'
    inputs:
      azureSubscription: $(azureSubscription)
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: if !(az group exists --name $resourceGroupName) ; then az group create --name $(resourceGroupName) --location $(region) --tags LastDeployed=$(runDateTime) Organization=$(orgPrefix) Application=$(appPrefix) Environment=$(environmentNameUpper) ; fi

  - task: AzureResourceManagerTemplateDeployment@3
    displayName: 'Publish Bicep Resources'
    inputs:
      csmFile: $(templateFile)
      overrideParameters: >
        -appPrefix $(appPrefix) 
        -environment $(environmentNameLower)
        -longAppName $(longAppName)
        -shortAppName $(shortAppName)
        -location $(region)
        -translationServiceKey $(translationServiceKey)
        -dockerRegistryServerUrl $(dockerRegistryServerUrl)
        -dockerRegistryServerUserName $(dockerRegistryServerUserName)
        -dockerRegistryServerPassword $(dockerRegistryServerPassword)
      deploymentScope: 'Resource Group'
      azureResourceManagerConnection: $(azureSubscription)
      action: 'Create Or Update Resource Group'
      resourceGroupName: '$(resourceGroupName)'
      location: '$(region)'
      templateLocation: 'Linked artifact'
      deploymentMode: 'Incremental'

  - task: AzureCLI@2
    displayName: 'Create Resource Group if not exists'
    inputs:
      azureSubscription: $(azureSubscription)
      scriptType: 'pscore'
      scriptLocation: inlineScript
      inlineScript: |
        $subscription = "$(azureSubscriptionId)"
        $ResourceGroupName = "$(resourceGroupName)"
        $sysTopicName = "$(SysTopicName)"
        $eventSubName = "$(EventGridSubName)"

        $LogicAppName = "$(LogicAppsName)"
        $MyWorkflow = "$(WorkflowName)"
            
        $workflowDetails = az rest --method post --uri https://management.azure.com/subscriptions/$subscription/resourceGroups/$ResourceGroupName/providers/Microsoft.Web/sites/$LogicAppName/hostruntime/runtime/webhooks/workflow/api/management/workflows/$MyWorkflow/triggers/When_a_resource_event_occurs/listCallbackUrl?api-version=2018-11-01
        $endPointURL = ($workflowDetails | ConvertFrom-Json).value
        
        Write-Host "Logic App url : $endPointURL"
        $restEventSubURL = "https://management.azure.com/subscriptions/$subscription/resourceGroups/$ResourceGroupName/providers/Microsoft.EventGrid/systemTopics/$sysTopicName/eventSubscriptions/$eventSubName"
        $restEventSubURL = $restEventSubURL + '?api-version=2021-06-01-preview'
        
        Write-Host "Event Sub url : $restEventSubURL"
        
        $body="{'properties': {'destination': {'endpointType':'WebHook','properties': {'endpointUrl':'$endPointURL'}},'filter': {'isSubjectCaseSensitive': false,'subjectBeginsWith': '/blobServices/default/containers/containerName/blobs','includedEventTypes': ['Microsoft.Storage.BlobCreated']}}}"
        
        az rest --method put --uri $restEventSubURL --body $body --headers Content-Type='application/json'







